transform:
    resize_dim: 399
    crop_dim: 300
train:
    batch_size: 64
    loss: 'ecc'
    epoch_interval: 1
    num_epochs: 3
    lamda1: 0.01
    lamda2: 1.2
    enable_lr_decay: False
    lr_step: 10
    lr_decay: 0.1
    ecc_alpha: 0.5
    shared_space_numfeats: 4096
model:
    name: 'resnet18'
    optimizer: 'Adam'
    lr: 0.00001
    weight_decay: 0.00001
    amsgrad: True
    momentum: 0.8
    build_on_pretrained: False
    pretrained_filename: '/models/checkpoints/last_model.pt'
dataset:
    size: 'subset'
