transform:
    resize_dim: 256
    crop_dim: 224
train:
    batch_size: 32
    loss: 'cross-entropy'
    epoch_interval: 1
    num_epochs: 1
model:
    name: 'alexnet'
    optimizer: 'Adam'
    lr: 0.001
    weight_decay: 0.0000001
    amsgrad: True
    momentum: 0.8
    build_on_pretrained: False
    pretrained_filename: '/models/checkpoints/last_model.pt'
dataset:
    size: 'subset'
