transform:
    resize_dim: 256
    crop_dim: 224
train:
    batch_size: 32
    k: 3
    loss: 'l1'
    epoch_interval: 5
    num_epochs: 10
model:
    name: 'alexnet'
    optimizer: 'Adam'
    lr: 0.0001
    weight_decay: 0.0000001
    amsgrad: True
    momentum: 0.8
    build_on_pretrained: False
    pretrained_filename: '/models/checkpoints/last_model.pt'
dataset:
    size: 'subset'
