transform:
    resize_dim: 399
    crop_dim: 300
train:
    batch_size: 64
    loss: 'ecc'
    epoch_interval: 5
    num_epochs: 20
    lamda1: 0.7
    lamda2: 0.05
    enable_lr_decay: False
    lr_step: 10
    lr_decay: 0.1
    ecc_alpha: 0.5
    shared_space_numfeats: 4096
model:
    name: 'alexnet'
    optimizer: 'Adam'
    lr: 0.0001
    weight_decay: 0.0000001
    amsgrad: True
    momentum: 0.8
    build_on_pretrained: False
    pretrained_filename: '/models/checkpoints/last_model.pt'
dataset:
    size: 'full'
